version: '3.8'

services:
  backend:
    # Le dice al constructor: "Ve a la caja ./backend y arma la cocina"
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3001:3001"
    environment:
      TZ: America/Lima
    networks:
      - appnet

  frontend:
    # Le dice al constructor: "Ve a la caja ./frontend y arma el comedor"
    build: ./frontend
    container_name: frontend_app
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge