version: '3.8'

sservices:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      TZ: America/Lima
    networks:
      - appnet

  frontend:
    build: ./frontend
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge