version: '3.8'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8519
      MYSQL_DATABASE: super_pollo_hyo
      TZ: America/Lima
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "3001:3001"
    environment:
      TZ: America/Lima
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge